// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-08-31 09:31:36.737465833 +0800 CST m=+0.043159820

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "在线客服API文档的文档，接管了微信公众号聊天",
        "title": "在线客服API文档",
        "contact": {},
        "license": {},
        "version": "0.0.1"
    },
    "basePath": "/",
    "paths": {
        "/v1/dialog": {
            "get": {
                "description": "获取待回复消息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dialog"
                ],
                "summary": "获取待回复消息列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "发送消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dialog"
                ],
                "summary": "发送消息",
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/dialog/ack": {
            "put": {
                "description": "确认已读",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dialog"
                ],
                "summary": "确认已读",
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/dialog/{customerId}": {
            "get": {
                "description": "获取聊天记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dialog"
                ],
                "summary": "获取聊天记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户 ID",
                        "name": "customerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/health": {
            "get": {
                "description": "应用程序健康检查接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Default"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/init": {
            "get": {
                "description": "在线客服系统进行初始化",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Default"
                ],
                "summary": "系统初始化",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/kf/{kfId}": {
            "get": {
                "description": "获取客服信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kf"
                ],
                "summary": "获取客服信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客服的ID",
                        "name": "kfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/kf/{kfId}/status": {
            "put": {
                "description": "客服修改在线状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kf"
                ],
                "summary": "客服修改在线状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客服的ID",
                        "name": "kfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/login/{tokenId}": {
            "post": {
                "description": "客服登入",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kf"
                ],
                "summary": "客服登入",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客服的授权TokenId",
                        "name": "tokenId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/setting/offline_reply": {
            "get": {
                "description": "获取自动回复列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OfflineReply"
                ],
                "summary": "获取自动回复列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "新增一条离线自动回复语句",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OfflineReply"
                ],
                "summary": "新增一条离线自动回复语句",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/setting/offline_reply/{id}": {
            "put": {
                "description": "更新一条离线自动回复语句",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OfflineReply"
                ],
                "summary": "更新一条离线自动回复语句",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "自动回复语句的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除一条离线自动回复语句",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OfflineReply"
                ],
                "summary": "删除一条离线自动回复语句",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "自动回复语句的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/wait_queue": {
            "get": {
                "description": "待接入列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WaitQueue"
                ],
                "summary": "待接入列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/wait_queue/access": {
            "post": {
                "description": "会话确认应答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WaitQueue"
                ],
                "summary": "会话确认应答",
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
